# Generated by Django 4.1.6 on 2023-03-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowUser',
            new_name='FollowersCount',
        ),
    ]
