# Generated by Django 4.1.6 on 2023-03-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
