# Generated by Django 4.1.6 on 2023-03-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
